[wip] Prototype of system for submission using only an email address
YunoHost/Simone pull request #4
Opened 2017-05-15 03:32 UTC by alexAubin

### Status

Still work in progress but the mosf ot the stuff is there

### Problem

From what I understand, Simone was meant to allow easy editing of the documentation, but fact is that it's not easy (you either need an account, the 'email' is weird (?)). The only option that really works is to do a fork/PR on git, but this increases the cost of contributions.

### Solution / Proposal

Allow people to edit online, then submit their changes to a 'bot' which will create the PR for them. To fight spam, people need to provide their email address and click on a link in the email to confirm the submission. Then a PR is created automatically.

We need to be careful though about sanitizing the user inputs, since some commands which are executed could be hacked with injections and/or rely on 'sudo' / ssh keys. Right now everything is not entirely secured.

2017-05-15 03:33 UTC, alexAubin commented
Also, a screenshot of how it now looks when you click "Send" : https://framapic.org/wjmJ9c2RZUV3/z8keIBSIFHbs.png

2017-05-17 21:41 UTC, alexAubin commented
This is now functional and ready for feedback (and possibly deployment). We could improve the i18n and format of emails sent and the confirm page but that's kind of a minor detail I think. I'm not really at ease with PHP but I tried to secure/sanitize the inputs such that no arbitrary code is possible. I also removed the necessity to use "sudo" and the dependency to the 'hub' thing from Github since it's crap and curl does the job pretty well.

The current backend codebase could also be cleaned and improved but since Simone is migrated to some other system (Django ?) it's probably not worth the pain.

2017-05-19 11:44 UTC, Jibec commented
Thanks for this work.
I don't know how to test this, I would love to get stats to see how much it helps.

Can the commit message get an explicit prefix so we can filter it?

In screenshot, you write "just a few more steps", but I only see one.

We should probably be explicit about the language to use for the comment (I assume English)
We should probably give a hint about what's coming next. The user edits, send form and then? What happened if it isn't accepted or if something is missing?

2017-07-10 15:37 UTC, alexAubin commented
>I don't know how to test this, 

I have a test server, to which I can point you to if you ask for it in private

>Can the commit message get an explicit prefix so we can filter it?

The pull request already has a [Anonymous contrib] prefix when it's created

>In screenshot, you write "just a few more steps", but I only see one.

>We should probably give a hint about what's coming next. The user edits, send form and then? What happened if it isn't accepted or if something is missing?

That's because you need to give your email, provide a description, then click in a link you received by email to validate the PR creation. The ? next to the 'Email' field tells you this. It also tells you about the email validation once you click on Submit.

>We should probably be explicit about the language to use for the comment (I assume English)

Imho the submitter should just use the language he/she thinks is the most appropriate (you might edit a page in english, in french, or even another language)

2017-07-18 19:05 UTC, zamentur reviewed
Principle approval +1
Small reviewed in the past (it was ok for me)

2017-07-18 19:06 UTC, zamentur approved these changes

2017-07-19 02:22 UTC, Psycojoker commented on index.php
> -<title><?php echo $title ?></title>
Why?

2017-07-19 02:25 UTC, Psycojoker commented on index.php
> -<title><?php echo $title ?></title>
Oh okay, it's not in the final diff.

2017-07-19 03:11 UTC, Psycojoker requested changes

2017-07-19 03:11 UTC, Psycojoker commented on confirm.php
> +// FOR DEBUGGING, NOT FOR PROD !!
"hu ho"

2017-07-19 03:11 UTC, Psycojoker commented on confirm.php
> +$email_from  = "yunobot@some.domain.tld";
Well, that doesn't look good.

2017-07-19 03:11 UTC, Psycojoker commented on confirm.php
> +        // FIXME sanitize inputs ?
That sound good no :yum:?

2017-07-19 03:11 UTC, Psycojoker commented on confirm.php
> +             'sudo /var/www/Simone/hub/bin/hub pull-request -m "[anonymous contrib] '.$descr.'" > ../'.$PRurl;
not sure if this can happen but I would preventively quote every shell variable to avoid white space of injection problems.

2017-07-19 03:11 UTC, Psycojoker commented on confirm.php
> +             'sudo /var/www/Simone/hub/bin/hub pull-request -m "[anonymous contrib] '.$descr.'" > ../'.$PRurl;
That also really looks hackish but I don't know if a better method exists :confused:

2017-07-19 03:11 UTC, Psycojoker commented on confirm.php
> +        $email_to      = $email;
I'm not sure if this needs to be sanitized but it really worth it checking to avoid headers injections.

2017-07-19 03:11 UTC, Psycojoker commented on index.php
> -    $content = Markdown($markdown);
Why all this php have been removed? That really doesn't seems linked to this PR.

2017-07-19 03:11 UTC, Psycojoker commented on submit.php
> +error_reporting(E_ALL);
"huho" again.

2017-07-19 03:11 UTC, Psycojoker commented on submit.php
> +    $simone_root = "https://some.domain.tld/simone/";
Again, since we don't have any settings I guess those needs to be changed.

2017-07-19 03:11 UTC, Psycojoker commented on submit.php
> +        // FIXME limit 'descr' characters and length ?
bladibla

2017-07-19 03:13 UTC, Psycojoker commented
Okay, github has been doing weird thing and I end up reviewer the wrong things, I'll redo that tomorrow, sorry for the noise :confused:

2017-07-24 19:58 UTC, opi commented on _js/app.js
> +                console.log(xhr);
please remove console.log

2017-07-24 19:59 UTC, opi commented on common.php
> +
php could be stupid with empty line before opening tag, please remove it.

2017-07-24 20:00 UTC, opi commented on common.php
> +    $page = file_get_contents('_pending_contrib/'.$id.'/page');
chekc & sanitize $id before calling file_get_contents() with this spoofable _SERVER variable

2017-07-24 20:01 UTC, opi commented on confirm.php
> +        shell_exec("./createPR.sh ".$id);
!FEAR!

2017-07-28 00:10 UTC, Psycojoker commented on createPR.sh
> +set -eu
Might want to set "x" too

2017-07-28 00:11 UTC, Psycojoker commented on createPR.sh
> +readonly REPO_TOKEN=$(cat $SIMONE_ROOT/config/github_token)
shouldn't all of those be in a configuration file or something to avoid having to stash when pulling?

2017-07-28 00:29 UTC, Psycojoker approved these changes
That's not really my field of expertise but that should be good from here.

2017-07-30 12:25 UTC, merged

2017-07-30 12:26 UTC, alexAubin commented
Deployed on bearnaise in a LXC + made the migration for yunohost.org.

Yunohost.org is now on bearnaise /o/